-- CONTAS A RECEBER DETALHADO (FILTRADO POR 1 ANO)
SELECT 
    r.REC_NUMEROOPERACAO,
    r.REC_NUMERONOTAFISCAL,
    r.REC_DATAEMISSAO,
    r.CLI_CODIGO,
    (SELECT c.CLI_NOME FROM CLIENTE c WHERE c.CLI_CODIGO = r.CLI_CODIGO) AS CLI_NOME,
    d.RED_PARCELA,
    d.RED_DATAVENCIMENTO,
    d.RED_VALORPARCELA,
    d.RED_VALORRECEBIDO,
    d.RED_DATARECEBIMENTO,
    r.REC_HISTORICO
    FROM RECDET d
    JOIN RECEBER r ON d.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO
    WHERE d.RED_DATAVENCIMENTO BETWEEN :DATA_INI AND :DATA_FIM
    ORDER BY d.RED_DATAVENCIMENTO
