-- CONTAS A PAGAR DETALHADO (FILTRADO POR 1 ANO)
SELECT 
    p.PAG_NUMEROOPERACAO,
    p.PAG_DOCTO,
    p.PAG_DATAEMISSAO,
    p.FOR_CODIGO,
    (SELECT f.FOR_NOME FROM FORNECEDOR f WHERE f.FOR_CODIGO = p.FOR_CODIGO) AS FOR_NOME,
    d.PAD_PARCELA,
    d.PAD_DATAVENCIMENTO,
    d.PAD_VALORPARCELA,
    d.PAD_VRTOTALPAGO,
    p.PAG_HISTORICO
FROM PAGDET d
JOIN PAGAR p ON d.PAG_NUMEROOPERACAO = p.PAG_NUMEROOPERACAO
WHERE p.PAG_DATAEMISSAO >= '2024-01-01'
ORDER BY d.PAD_DATAVENCIMENTO
