-- CONTAS A RECEBER EM ABERTO (OTIMIZADO COM CAMPO DINAMICO)
SELECT 
    r.REC_NUMEROOPERACAO,
    r.PED_NUMEROOPERACAO AS REC_NUMEROPEDIDO,
    r.REC_NUMERONOTAFISCAL,
    r.REC_DATAEMISSAO,
    r.CLI_CODIGO,
    c.CLI_NOME,
    d.RED_PARCELA,
    d.RED_DATAVENCIMENTO,
    d.RED_VALORPARCELA,
    d.RED_VALORRECEBIDO,
    ult_rec.REB_DATARECEBIMENTO AS DATA_REC_REAL,
    ult_rec.TPF_SIGLA AS TPF_RECEBIDO,
    r.REC_HISTORICO
FROM RECDET d
JOIN RECEBER r ON d.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO
LEFT JOIN CLIENTE c ON c.CLI_CODIGO = r.CLI_CODIGO
LEFT JOIN (
    SELECT 
        rt.REC_NUMEROOPERACAO, 
        rt.RED_PARCELA, 
        MAX(rt.REB_DATARECEBIMENTO) as REB_DATARECEBIMENTO,
        MAX(rt.TPF_SIGLA) as TPF_SIGLA -- Simplifica para performance
    FROM RECEBTO rt
    GROUP BY rt.REC_NUMEROOPERACAO, rt.RED_PARCELA
) ult_rec ON ult_rec.REC_NUMEROOPERACAO = d.REC_NUMEROOPERACAO AND ult_rec.RED_PARCELA = d.RED_PARCELA
WHERE (d.RED_VALORRECEBIDO < d.RED_VALORPARCELA)
  AND :CAMPO_DATA BETWEEN :DATA_INI AND :DATA_FIM
ORDER BY :CAMPO_DATA
