-- EXTRATO UNIFICADO (KARDEX) - OTIMIZADO COM JOINS E FILTRO 1 ANO
SELECT 
    mov.PROD_CODIGO AS "COD_PRODUTO",
    prod.PROD_DESCRICAOPRODUTO AS "DESCRICAO",
    mov.DATA_MOV AS "DATA",
    mov.TIPO,
    mov.DOCUMENTO,
    mov.ENTIDADE_COD AS "COD_ENTIDADE",
    mov.ENTIDADE_NOME AS "NOME_ENTIDADE",
    mov.QTDE,
    mov.VALOR_UNIT,
    mov.TOTAL
FROM (
    -- SAÍDAS (VENDAS)
    SELECT 
        i.PROD_CODIGO,
        p.PED_DATAVENDA as DATA_MOV,
        'SAIDA (VI)' as TIPO,
        CAST(p.PED_NUMEROPEDIDO AS VARCHAR(20)) as DOCUMENTO,
        p.CLI_CODIGO as ENTIDADE_COD,
        c.CLI_NOME as ENTIDADE_NOME,
        i.PIT_QTDEVENDIDA as QTDE,
        i.PIT_VALORUNITARIO as VALOR_UNIT,
        (i.PIT_QTDEVENDIDA * i.PIT_VALORUNITARIO) as TOTAL
    FROM PEDITENS i
    JOIN PEDIDO p ON i.PED_NUMEROOPERACAO = p.PED_NUMEROOPERACAO
    LEFT JOIN CLIENTE c ON p.CLI_CODIGO = c.CLI_CODIGO

    UNION ALL

    -- ENTRADAS (COMPRAS)
    SELECT 
        i.PROD_CODIGO,
        e.ENT_DATAENTRADA as DATA_MOV,
        'ENTRADA (EE)' as TIPO,
        CAST(e.ENT_NUMERONOTAFISCAL AS VARCHAR(20)) as DOCUMENTO,
        e.FOR_CODIGO as ENTIDADE_COD,
        f.FOR_NOME as ENTIDADE_NOME,
        i.ENI_QTDEENTRADA as QTDE,
        i.ENI_VALORUNITARIO as VALOR_UNIT,
        (i.ENI_QTDEENTRADA * i.ENI_VALORUNITARIO) as TOTAL
    FROM ENTITENS i
    JOIN ENTRADA e ON i.ENT_NUMEROOPERACAO = e.ENT_NUMEROOPERACAO
    LEFT JOIN FORNECEDOR f ON e.FOR_CODIGO = f.FOR_CODIGO
) mov
JOIN PRODUTO prod ON mov.PROD_CODIGO = prod.PROD_CODIGO
ORDER BY 1, 3
