SELECT FIRST 20 
    '1' AS "Empresa",
    r.REC_NUMEROPEDIDO AS "Número da Duplicata",
    r.REC_NUMERONOTAFISCAL AS "Número da NF",
    r.CLI_CODIGO AS "Código do Cliente",
    COALESCE(NULLIF(TRIM(c.CLI_CPF), ''), NULLIF(TRIM(c.CLI_CNPJ), '')) AS "CNPJ/CPF",
    c.CLI_NOME AS "Descrição do Cliente",
    d.RED_PARCELA AS "Parcela da Duplicata",
    r.REC_DATAEMISSAO AS "Data de Movimento",
    d.RED_DATAVENCIMENTO AS "Data de Vencimento",
    d.RED_VALORPARCELA AS "Valor da Duplicata",
    '' AS "Ocorrência",
     COALESCE((SELECT FIRST 1 rt.TPF_SIGLA FROM RECEBTO rt WHERE rt.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO AND rt.RED_PARCELA = d.RED_PARCELA ORDER BY rt.REB_DATARECEBIMENTO DESC), '') AS "Forma de Pagamento",
    COALESCE((SELECT SUM(rt.REB_DESCONTO) FROM RECEBTO rt WHERE rt.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO AND rt.RED_PARCELA = d.RED_PARCELA), 0) AS "Desconto",
    COALESCE((SELECT SUM(rt.REB_JUROS + COALESCE(rt.REB_MULTA, 0)) FROM RECEBTO rt WHERE rt.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO AND rt.RED_PARCELA = d.RED_PARCELA), 0) AS "Valor Juros Cobrado",
    0 AS "% Juros Mora Diário",
    d.RED_VALORRECEBIDO AS "Valor Pago",
    (SELECT MAX(rt.REB_DATARECEBIMENTO) FROM RECEBTO rt WHERE rt.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO AND rt.RED_PARCELA = d.RED_PARCELA) AS "Data de Pagamento",
    d.RED_NUMEROBOLETO AS "Nosso Número",
    r.REC_HISTORICO AS "Histórico"
FROM RECDET d
JOIN RECEBER r ON d.REC_NUMEROOPERACAO = r.REC_NUMEROOPERACAO
LEFT JOIN CLIENTE c ON c.CLI_CODIGO = r.CLI_CODIGO
WHERE (d.RED_VALORRECEBIDO < d.RED_VALORPARCELA)
